# Set the base image
FROM node:20

# Set working directory
WORKDIR /var/www

# Copy `package.json` and `package-lock.json`
COPY package*.json ./

# Install project dependencies
RUN npm install --include=dev

RUN npm install @floating-ui/dom portal-vue@next chart.js@^3.7.0 vue-good-table npm v-pagination vite-plugin-html
# Copy project files into the docker image
COPY . .

# Expose the port Vite runs on
EXPOSE 3000

# Start the Vite server
CMD ["npm", "run", "dev"]